name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      dotnet-version: 6.0.x
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: restore .NET dependencies
      run: dotnet restore amadeus-csharp.sln
    - name: Build the Solution
      run: | 
        dotnet build amadeus-csharp.sln --configuration Release -p:platform="Any CPU" --no-restore
    - name: run UnitTests
      run: dotnet test ./amadeus-test/amadeus-test.csproj --configuration Release --no-build --no-restore